apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
data:
  telegram_bot_id: "<Telegram Bot token>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferrucciofacts-bot
  labels:
    app: ferrucciofacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferrucciofacts
  template:
    metadata:
      labels:
        app: ferrucciofacts
    spec:
      containers:
      - name: ferrucciofacts
        image: mastrogiovanni/ferrucciofacts
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TELEGRAM_BOT_ID
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: telegram_bot_id
